### ISSUE TITLE
dummy example doesn't work for me

### ISSUE THREAD

**Issue by RJuro** [oborchers/Fast_Sentence_Embeddings#1]
Thanks for that package. Very much needed work :-)

`se.train(sentences)`
gives: `TypeError: s2v_train() takes 3 positional arguments but 4 were given`

I was trying it on Google Colab

**Comment by oborchers** [comment]
Hi Roman,

thank you for finding this bug. I forgot to modify the non-cyhton version. You ran into the non-Cython version, which is way slower. That made me realize the Cython compilation doesn't work on Colab. You have to build from git using:

pip install git+https://github.com/oborchers/Fast_Sentence_Embeddings

See https://colab.research.google.com/drive/1qq9GBgEosG7YSRn7r6e02T9snJb04OEi for an example.

**Comment by RJuro** [comment]
Awesome, thanks. 👍🏻

**Comment by oborchers** [comment]
@RJuro : I've updated the package to v.0.1.1. The dummy example on [Colab](https://colab.research.google.com/drive/1qq9GBgEosG7YSRn7r6e02T9snJb04OEi) shows how to install and upgrade to the new version 👍

**Comment by RJuro** [comment]
Great. Thanks
