### ISSUE TITLE
C extension not loaded, training/inferring will be slow

### ISSUE THREAD

**Issue by DXcarlos** [oborchers/Fast_Sentence_Embeddings#18]
Hi, I've installed fse in Windows I get the following warning 
C:\Users\CARLOS\Anaconda3\lib\site-packages\fse\models\base_s2v.py:115: UserWarning: C extension not loaded, training/inferring will be slow. Install a C compiler and reinstall fse.
  "C extension not loaded, training/inferring will be slow. "

I know that this type of warning also appears in gensim in some cases, however, in gensim I don't have this problem. Does anyone have any idea what should I do?

My results on gensim
>from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1

My training speed is :

training on 571201 effective sentences with 4590776 effective words took 28s with 19703 sentences/s

**Comment by oborchers** [comment]
Hi @DXcarlos,

unfortunately I have currently no way of implementing or testing the fse library on Windows to be honest. This is something for a future release, as building the C core routines for computing the embeddings is not compiled on windows and reverts to a pure numpy implementation, which is way too slow.

**Comment by mavrokefalidis** [comment]
I have this same problem in a Mac OS

**Comment by AlexMRuch** [comment]
I also have this issue on Mac OS
