### ISSUE TITLE
train on data and predict on new data

### ISSUE THREAD

**Issue by spedygiorgio** [oborchers/Fast_Sentence_Embeddings#2]
Hi I see that the train method of an fse object returns the sentence embedding.
Is threre a predict method to apply the trained modeled on new data?
Or train stays for predict?

Best

**Comment by oborchers** [comment]
Hi! Train is the equivalent of the predict function. However, I think I will rename the function to „infer“ in a future version.

**Comment by spedygiorgio** [comment]
thank you

**Comment by oborchers** [comment]
@spedygiorgio 
I have included a train and a predict method. Some embeddings (SIF, uSIF) require the estimation of components, which is performed during training. If you apply infer to a new set of sentences it will only remove the components, but not re-estimate the components. 

See the [notebook](https://github.com/oborchers/Fast_Sentence_Embeddings/blob/master/notebooks/Tutorial.ipynb) for an example
