### ISSUE TITLE
Is it possible to use customised word frequency other than the one comes with model and lang_freq option?

### ISSUE THREAD

**Issue by zheyaf** [oborchers/Fast_Sentence_Embeddings#25]
Hi, I have a word frequency dictionary independent from the model I trained, is it possible to have the option to feed sif with a word frequency dictionary separately? Thanks!

**Comment by oborchers** [comment]
@zheyaf : Thanks for asking. Currently this feature is not supported. Yet, you can manipulate the ingoing model to contain your own frequencies. For an example, see [here](https://github.com/oborchers/Fast_Sentence_Embeddings/blob/6f9febf806ec321bb0e2f0ad1168fcc7a7f2647e/fse/models/base_s2v.py#L264)
