### ISSUE TITLE
gensim model of Paranmt

### ISSUE THREAD

**Issue by kyoungrok0517** [oborchers/Fast_Sentence_Embeddings#28]
Hi, could I have the gensim model of Paranmt you've used in STS demo? I've found the original vector pickle from the authors homepage (http://www.cs.cmu.edu/~jwieting/) but I don't know how to convert it to gensim model. Thanks for the great work!

**Comment by oborchers** [comment]
Hi,

I've converted the model of Wieting to a Gensim model. Download the model here: 

https://www.dropbox.com/sh/xr9h13u1ek2dcyd/AADeTEgpf1LRZFWosPNXx93La?dl=0
