### ISSUE TITLE
cannot import name 'Sentence2Vec' from 'fse.models'

### ISSUE THREAD

**Issue by amandalmia14** [oborchers/Fast_Sentence_Embeddings#29]
Hi @oborchers ,

Post installing fse on windows by `pip install fse` when I try to import ` from fse.models import Sentence2Vec`

It throws the following error, 
`cannot import name 'Sentence2Vec' from 'fse.models' (d:\amandalmia\venv\lib\site-packages\fse\models\__init__.py)`

Can you please help me in this issue. 
Source: https://towardsdatascience.com/fse-2b1ffa791cf9

Thanks.

**Comment by victorBigand** [comment]
Hi,
The code in the article is deprecated and the Sentence2Vec class does not exist anymore.
You can refer to this notebook to get up and running quickly: https://github.com/oborchers/Fast_Sentence_Embeddings/blob/master/notebooks/Tutorial.ipynb

**Comment by oborchers** [comment]
Yes, @victorBigand is correct. I am going to write a doc as soon as I've got some spare time. Am focussing on more important features first.
