### ISSUE TITLE
Docs: extend example with lookup

### ISSUE THREAD

**Issue by DarrenCook** [oborchers/Fast_Sentence_Embeddings#3]
It would be great if you could show how to use the sentence embeddings, e.g. to find the nearest sentence, or nearest N sentences, in the training corpus. I.e. how to write `find_nearest()` in the below:

```
from gensim.models import Word2Vec
sentences = [["cat", "say", "meow"], ["dog", "say", "woof"]]
model = Word2Vec(sentences, min_count=1)

from fse.models import Sentence2Vec
se = Sentence2Vec(model)
sentences_emb = se.train(sentences)

test_sentence = [["dog", "say", "moo"]]
find_nearest(sentences_emb, test_sentence)
```

**Comment by oborchers** [comment]
Thank you for the suggestion! I am currently thinking of some major changes to the library, thus this would be a welcome enhancement.

**Comment by DarrenCook** [comment]
Thanks for the reply: If there is nothing built into fse currently, I wondered if `sentences_emb` could be used with the gensim word2vec functions for finding nearest matches? But it must be a 2-step process?? (I took a look at the  Sentence_Prediction.ipynb file, but couldn't see what I needed.)

**Comment by oborchers** [comment]
The simplest way of comparing sentences currently would be to compute the l2 normalized matrix-vector product of sentences_emb.dot(test_sentence) and look for the top-n values. I will add tha tin a future version

**Comment by yondu22** [comment]
```
from gensim.models import Word2Vec
from termcolor import colored
import numpy as np


def find_nearest(sentence_embeddings, test_sentence_vec, topk, sentences, test_sentence):
	# compute normalized dot product as score
	score = np.sum(test_sentence_vec * sentence_embeddings, axis=1) / np.linalg.norm(sentence_embeddings, axis=1)
	topk_idx = np.argsort(score)[::-1][:topk]
	print('top %d questions similar to "%s"' % (topk, colored(test_sentence, 'green')))
	for idx in topk_idx:
		print('> %s\t%s' % (colored('%.1f' % score[idx], 'cyan'), colored(sentences[idx], 'yellow')))

topk = 5
prefix_q = '##### **Q:** '
sentences = [["cat", "say", "meow"], ["dog", "say", "woof"]]
model = Word2Vec(sentences, min_count=1)

from fse.models import Sentence2Vec
se = Sentence2Vec(model)
sentences_emb = se.train(sentences)

test_sentence = [["dog", "say", "moo"]]
query_vec =se.train(test_sentence)[0]
find_nearest(sentences_emb, query_vec, topk, sentences, test_sentence)
```

**Comment by DarrenCook** [comment]
@yondu22  Thanks! I've been testing with this, and I think it needs one small fix (before the `np.argsort` line):

    score = np.absolute(score)

(BTW, for a minimal documentation example, I think the termcolor dependency should be dropped.)

**Comment by yondu22** [comment]
thanks, good point

**Comment by oborchers** [comment]
@DarrenCook and @yondu22:
I have implemented a method to search for similar sentences in the latest version v.0.1.1. 
See the jupyter [notebook](https://github.com/oborchers/Fast_Sentence_Embeddings/blob/master/notebooks/Tutorial.ipynb) for an example.
Yours
