### ISSUE TITLE
Bug in remove_principal_components

### ISSUE THREAD

**Issue by antklen** [oborchers/Fast_Sentence_Embeddings#35]
https://github.com/oborchers/Fast_Sentence_Embeddings/blob/6f9febf806ec321bb0e2f0ad1168fcc7a7f2647e/fse/models/utils.py#L135

For inplace = False function returns projection on principal components instead of resulting vectors.

**Comment by oborchers** [comment]
Thank you for raising the issue! I will have a look into this

**Comment by bhargavvader** [comment]
Has this by been fixed? I believe the fix by @grantmwilliams [here](https://github.com/grantmwilliams/Fast_Sentence_Embeddings/commit/ad88c812f36b935c23c2ebc018eb20a7876a7fb0) should do the trick. Should I raise a PR if that makes things easier for you @oborchers ?

**Comment by grantmwilliams** [comment]
> Has this by been fixed? I believe the fix by @grantmwilliams [here](https://github.com/grantmwilliams/Fast_Sentence_Embeddings/commit/ad88c812f36b935c23c2ebc018eb20a7876a7fb0) should do the trick. Should I raise a PR if that makes things easier for you @oborchers ?

https://github.com/oborchers/Fast_Sentence_Embeddings/pull/37 Was merged and should have the fix.

**Comment by bhargavvader** [comment]
Great!

**Comment by oborchers** [comment]
Yes! thanks for your contribution
