### ISSUE TITLE
Hierarchical pooling

### ISSUE THREAD

**Issue by lambdaofgod** [oborchers/Fast_Sentence_Embeddings#39]
Could you say something more about hierarchical pooling? 
I am interested in this feature, but I'm not sure what you mean.
I can try to implement this if given some guidance.

**Comment by oborchers** [comment]
Hi @lambdaofgod ! Thanks for your interest! Hierarchical pooling means averaging over a subspan of the original tokens. For example:
> Hello - how - are - you - doing
> avg1: (hello - how - are) / 3
> avg2: (how - are - you) / 3
> vec: (avg1 + avg2) / 2

I added this feature a while on the dev branch, but have to admit that the branch is somewhat abandoned.
https://github.com/oborchers/Fast_Sentence_Embeddings/blob/develop/fse/test/test_pooling.py

**Comment by oborchers** [comment]
Please see discussion #49
