### ISSUE TITLE
Regarding comparison

### ISSUE THREAD

**Issue by jaytimbadia** [oborchers/Fast_Sentence_Embeddings#42]
Hi, Really great work!!

I just have one question.

Which one (FastText, word2vec, glove) is good in getting better sentence embedding from respective word vectors by averaging them?

Which according to you will give better results on search results for sentences if I embed them?

**Comment by oborchers** [comment]
Hi @jaytimbadia! This depends entirely on the application and the corpus. Different vectors may work better for different purposes. Please feel free to test multiple variants. Thanks!
