### ISSUE TITLE
cannot import name 'BaseKeyedVectors' from 'gensim.models.keyedvectors' 

### ISSUE THREAD

**Issue by rishabhrjain** [oborchers/Fast_Sentence_Embeddings#43]
I have installed gensim 3.8 and have python 3.7. 

Traceback:
------------------------------------------------------------------------------------
from fse.inputs import IndexedList, IndexedLineDocument
     11 
---> 12 from gensim.models.keyedvectors import BaseKeyedVectors
     13 
     14 from numpy import dot, float32 as REAL, memmap as np_memmap, \

ImportError: cannot import name 'BaseKeyedVectors' from 'gensim.models.keyedvectors' (/usr/local/lib/python3.7/dist-packages/gensim/models/keyedvectors.py)

-------------------------------------------------------------------------------------

I don't find any class called "BaseKeyedVectors" in gensim. Looks like its been changed to just "KeyedVectors" ?

**Comment by mengxiayu** [comment]
Maybe you can double check the version of gensim. I solved this problem by downgrading gensim to 3.8.3.

**Comment by oborchers** [comment]
This issue should be fixed in version `0.1.17`. Please reopen if necessary 👍
