### ISSUE TITLE
Encounter "Divided 0 Error"

### ISSUE THREAD

**Issue by JacksonWuxs** [oborchers/Fast_Sentence_Embeddings#47]
Hi Oliver,

Thanks to this great repo!
But, I found some issues when I use it with [SentEval](https://github.com/facebookresearch/SentEval).

Generally speaking, the problem is "divide by zero error" when I use `uSIF(glove, length=12, ncomponents=1)`. The error was raised at calculating `a = (1 - alpha)/(alpha * 2)` at the _fse/models/usif.py:line126_.

If you need a minimum running code to reproduce the error, please let me know.

**Comment by grantmwilliams** [comment]
@JacksonWuxs do you think you could post the minimum running code example? I think I'd like to take a look at addressing the problem.

**Comment by JacksonWuxs** [comment]
I will try to prepare it for several days.

**Comment by oborchers** [comment]
@JacksonWuxs should be fixed in 0.2.0. Please re-open if still present, wasn't able to replicate the issue given the arguments provided in the issue.
