### ISSUE TITLE
Paranmt Model

### ISSUE THREAD

**Issue by grantmwilliams** [oborchers/Fast_Sentence_Embeddings#48]
Is there any information on getting the `paranmt` model or setting it up? The benchmarks show it as a great model to use with FSE and I was hoping to try it out, but I haven't been able to find it anywhere (just training data). I was just curious if there was somewhere we could access this model/keyed vectors.

**Comment by oborchers** [comment]
Hi @grantmwilliams!

Back then I downloaded the `paranmt` model from here I think: https://www.cs.cmu.edu/~jwieting/ https://aclanthology.org/P18-1042.pdf

But I've found a zip on my computer. It looks incredibly small, so I uploaded it (barely 200mb, 72 words x 300d)

https://drive.google.com/file/d/1PMekZGfVsIdSN9q7qgw13M4mPQ_oiGTJ/view?usp=sharing

**Comment by oborchers** [comment]
@grantmwilliams I'm working on `0.2.0`. It will provide downloadable vectors, including these ones. Stay tuned.

**Comment by oborchers** [comment]
@grantmwilliams the model is now accessible using:

```
from fse import Vectors, Average

vecs = Vectors.from_pretrained("paranmt-300")
model = Average(vecs)
```
