### ISSUE TITLE
Add gensim 4.0.0 support

### ISSUE THREAD

**Issue by oborchers** [oborchers/Fast_Sentence_Embeddings#63]

**Comment by AleMuzzi** [comment]
Hi, on this purpose I made a pull request with Gensim >=4 support: https://github.com/oborchers/Fast_Sentence_Embeddings/pull/65

**Comment by oborchers** [comment]
Thanks @AleMuzzi! I will look into it and rewrite the tests 👍🏻

**Comment by AleMuzzi** [comment]
> Any chance of @AleMuzzi MR making into the main branch? Many projects now requires Gensim >=4.

Meanwhile you can update your Gensim using my fork with this command:

`pip install -U git+https://github.com/AleMuzzi/Fast_Sentence_Embeddings`

Hope it helps.

**Comment by oborchers** [comment]
@AleMuzzi @bratao I am painfully behind in maintenance. I will consider this issue tomorrow
