### ISSUE TITLE
from the Results, CBOW is best, therefore why use SIF?

### ISSUE THREAD

**Issue by MrRace** [oborchers/Fast_Sentence_Embeddings#66]
As far as know,  SIF(smooth inverse frequency) just modify the vectors trained by Word2Vec、Glove or other word vector methods.
Therefore why CBOW is best in the Results? If CBOW is best, why need SIF?

![image](https://user-images.githubusercontent.com/10300313/152940910-238c1e80-92b4-446b-a06d-97f1f0acddd6.png)

**Comment by oborchers** [comment]
@MrRace: This fully depends. Paranmt has a very small vocabulary, whereas you can have a much larger vocabulary with fasttext. So it depends on usecase and data.
